version: '3.9'

services:
  miapi:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=MiBase;User Id=appuser;Password=AppUserPass!2025;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./sql-init:/docker-entrypoint-initdb.d
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 4g

volumes:
  sql_data:

networks:
  backend:
